spring.application.name=skillgap

# actuator
management.endpoints.web.exposure.include=health, info
management.endpoint.health.show-details=always

# konfiguracja tymczasowa - h2 dla testow tylko
spring.datasource.url=jdbc:h2:file:./data/skillgapdb;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

#security
spring.security.user.name=user
spring.security.user.password=password
spring.security.user.roles=USER

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true

# Logging
logging.level.com.skillgap.service.SkillGapService=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36}.%M:%L - %msg%n

# Skill Analysis Service
skill-analysis.co-occurrence.candidate-pool=100

# Skill Gap Service
skill-gap.thresholds.must-have=50.0
skill-gap.thresholds.nice-to-have=15.0

skill-gap.weights.must-have=0.8
skill-gap.weights.nice-to-have=0.2

