spring.application.name=skillgap

# actuator
management.endpoints.web.exposure.include=health, info
management.endpoint.health.show-details=always

# database
spring.datasource.url=jdbc:postgresql://localhost:5433/skillgap_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false

    # Batching to optimize saving to database
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

#security
spring.security.user.name=user
spring.security.user.password=password
spring.security.user.roles=USER

# Logging
# logging.level.com.skillgap.service=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36}.%M:%L - %msg%n

# Skill Analysis Service
skill-analysis.co-occurrence.candidate-pool=100
skill-analysis.role-stacks.popularity-threshold=0.05

# Skill Gap Service
skill-gap.thresholds.must-have=50.0
skill-gap.thresholds.nice-to-have=15.0

skill-gap.weights.must-have=0.8
skill-gap.weights.nice-to-have=0.2

# Import Job Offers
app.import.scheduler.enabled=true
app.import.scheduler.cron=0 0 3 * * *

